### ISSUE TITLE
boto3 with elbv2 support

### ISSUE THREAD

**Issue by cmsd2** [aws/elastic-load-balancing-tools#1]
I doubt this'll be a surprise, but where do I get a version of boto that supports ALBs?

  File ".../elastic-load-balancing-tools/venv/local/lib/python2.7/site-packages/botocore/loaders.py", line 353, in load_service_model
    known_service_names=', '.join(sorted(known_services)))
botocore.exceptions.UnknownServiceError: Unknown service: 'elbv2'. Valid service names are: acm, apigateway, application-autoscaling, autoscaling, cloudformation, cloudfront, cloudhsm, cloudsearch, cloudsearchdomain, cloudtrail, cloudwatch, codecommit, codedeploy, codepipeline, cognito-identity, cognito-idp, cognito-sync, config, datapipeline, devicefarm, directconnect, discovery, dms, ds, dynamodb, dynamodbstreams, ec2, ecr, ecs, efs, elasticache, elasticbeanstalk, elastictranscoder, elb, emr, es, events, firehose, gamelift, glacier, iam, importexport, inspector, iot, iot-data, kinesis, kms, lambda, logs, machinelearning, marketplacecommerceanalytics, meteringmarketplace, opsworks, rds, redshift, route53, route53domains, s3, sdb, servicecatalog, ses, sns, sqs, ssm, storagegateway, sts, support, swf, waf, workspaces

**Comment by coltoncat** [comment]
Upgrading from pip will install the latest version - actually if you are also using the cli, then performing:

`$ pip install --upgrade awscli`

will update the CLI to 1.10.55, which includes support for elbv2.

**Comment by tipuq** [comment]
Using the latest available version resolves the issue as mentioned above. 

$ pip install --upgrade awscli
