### ISSUE TITLE
Dry Run doesn't work with Ireland Region

### ISSUE THREAD

**Issue by reecestart** [aws/elastic-load-balancing-tools#11]
The --dry-run option doesn't appear to work with the Ireland region.

user$ python copy_classic_load_balancer.py --name WINDOWS-TEST-ELB -–region eu-west-1 --dry-run
usage: copy_classic_load_balancer.py --name <elb name> --region
copy_classic_load_balancer.py: error: argument --region is required
user$ python copy_classic_load_balancer.py --name WINDOWS-TEST-ELB --dry-run
usage: copy_classic_load_balancer.py --name <elb name> --region
copy_classic_load_balancer.py: error: argument --region is required
user$ python copy_classic_load_balancer.py --name WINDOWS-TEST-ELB
usage: copy_classic_load_balancer.py --name <elb name> --region
copy_classic_load_balancer.py: error: argument --region is required
user$ python copy_classic_load_balancer.py --name WINDOWS-TEST-ELB --region eu-west-1
Your Application Load Balancer is ready!
Application Load Balancer ARN:
arn:aws:elasticloadbalancing:eu-west-1:12345678910:loadbalancer/app/WINDOWS-TEST-ELB/2245666360f9c5ce
Target group ARNs:
Considerations:
1. If your Classic load balancer is attached to an Auto Scaling group, attach the target groups to the Auto Scaling group.
2. All HTTPS listeners use the predefined security policy.
3. To use Amazon EC2 Container Service (Amazon ECS), register your containers as targets.
user$

**Comment by coltoncat** [comment]
Thank you, will take a look at this...

**Comment by danlindow** [comment]
The characters in "--region" are different between your first examples and the one that works at the end.  
<img width="1092" alt="screen shot 2017-07-18 at 1 08 36 am" src="https://user-images.githubusercontent.com/9800912/28286398-a9f68062-6b55-11e7-8b8c-e1fcffd0a74b.png">

In my terminal you will see that I am searching for --region and it does not match the first command. but it does match the second one.

Your first example is using the following unicode character
http://www.fileformat.info/info/unicode/char/2013/index.htm

Whereas the working example is not.

This should work:
python copy_classic_load_balancer.py --name WINDOWS-TEST-ELB --region eu-west-1 --dry-run

this wont:
python copy_classic_load_balancer.py --name WINDOWS-TEST-ELB -–region eu-west-1 --dry-run
