### ISSUE TITLE
flag for choosing which ELB to convert

### ISSUE THREAD

**Issue by chadmay** [aws/elastic-load-balancing-tools#12]
I don't see how this script can know which ELB should be converted to the ALB type. Maybe I'm missing something, but we have several ELBs in our account and being able to choose the one I want to convert, should be a flag where I can give the script the name of that ELB. Am I missing something?

**Comment by danlindow** [comment]
The -name argument is what will specify the ELB name it will attempt to copy.

**Comment by renlon** [comment]
As danlindow mentioned earlier, the option "name" gives you the option to choose which ELB to be converted to ALB. 
For example -- 
copy_classic_load_balancer.py --name my-load-balancer -–region us-west-2 --dry-run
