### ISSUE TITLE
botocore.exceptions.UnknownServiceError: Unknown service: 'nlb'

### ISSUE THREAD

**Issue by philenz** [aws/elastic-load-balancing-tools#16]
Hi there,

I'm getting an error telling me that nlb is an unknown service when trying to run ./copy_network_load_balancer.py.

I'm using...
boto3 (1.4.7)
botocore (1.7.7)

**Comment by danlindow** [comment]
I just created a Pull request that should fix this issue from occurring. I am working with the team to get this merged in. 

For now you can change line 514 in the script to the following:
client = session.create_client('elbv2', region_name=region)

Thank you for bringing this to our attention.

-Dan

**Comment by danlindow** [comment]
We have this merged in at this time. Can you pull down the latest commit and verify this exception is no longer raised?

Thanks!

-Dan

**Comment by philenz** [comment]
All good now.
Thanks for the quick response, Dan.
Happy for you to close this one :-)
