### ISSUE TITLE
Remind user to upgrade AWS CLI to lastest version

### ISSUE THREAD

**Issue by kyokoshome** [aws/elastic-load-balancing-tools#18]
HI, 

I use this script by this
`./copy_network_load_balancer.py --name demoCLB  --region ap-southeast-1 --register-targets`

and the script respond following error 
`2017-10-20 15:45:39,965 ERROR Parameter validation failed:
Unknown parameter in input: "Type", must be one of: Name, Subnets, SecurityGroups, Scheme, Tags, IpAddressType` 

User does not get useful information by this error message. It took a long time , I figure out that my AWS CLI is too old that it does not support  `aws  elbv2 create-load-balancer ` with type network.

In order not to waste anyone life, I suggest to highlight "Upgrade your AWS CLI first!!!!" in Readme.md

**Comment by renlon** [comment]
Thanks for the feedback. As you noted that the migration script requires botocore version 1.7.6 or later to support Network Load Balancer. Per your suggestion, we are going to add that int the README.md. Thanks again for your input.

**Comment by tipuq** [comment]
Closing this issue since we added the following note: "Please make sure that your botocore version number is higher than 1.7.6."
