### ISSUE TITLE
Copy without listner

### ISSUE THREAD

**Issue by salvaitor** [aws/elastic-load-balancing-tools#24]
Hello,

I used the tool to copy CLB to ALB, but the tool work without create one.
My CLb have two Listner, one https to http and http to http, the last one the tool forgot.

**Comment by renlon** [comment]
Hi salvaitor,

Thanks for using this tool. Is it possible for you to provide the log output or any error message you observed on your end? In the case of copying from CLB to ALB, this tool will copy CLB listener over to ALB listener and copy CLB backend listener accordingly to target listener. Have you checked if it created two target groups with your backend listener ports? 

Looking forward to your reply. 

Thank you!

**Comment by renlon** [comment]
Hi salvaitor,

I tested with utility with my own Classic Load Balancer, which has two listeners, one http to http, one https to http and the tool was able to create two target groups for each listener. I am resolving this issue for now. Please feel free to reopen this issue if it still exists on your end.
