### ISSUE TITLE
ELBSecurityPolicy is not copying to ALB

### ISSUE THREAD

**Issue by cahn1** [aws/elastic-load-balancing-tools#25]
My ELB Listener with 443 has set to ELBSecurityPolicy-TLS-1-2-2017-01. When I run copy_classic_load_balancer.py, SecurityPolicy is reset to ELBSecurityPolicy-2016-08. 

I see you mentioned below in README.
---
Addition considerations and best practices:
2.All HTTPS listeners created will be utilizing the AWS pre-defined cipher security policy. Please modify the HTTPS listener configurations if you need to use custom policies.
---

ELBSecurityPolicy-TLS-1-2-2017-01 is a pre-defined policy and it's not copied.
Can this be copied as well?

Thanks,
Kay

**Comment by renlon** [comment]
Hi cahn1,

Thanks for the feedback. The following pull request should be able to fix the issue. 
https://github.com/aws/elastic-load-balancing-tools/pull/29

Please note that the SSL policy of CLB and ALB are different. If the source CLB uses a SSL policy that is not supported by ALB, then the tool will return "SSLPolicyNotFound" error. 

SSL Security Policies for Classic Load Balancers:
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-security-policy-table.html

SSL Security Policies for Application Load Balancers:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html

**Comment by renlon** [comment]
Resolving this issue for now. Please feel free to reopen it if you observe any issue. Thanks again.
