### ISSUE TITLE
botocore.exceptions.UnknownServiceError: Unknown service: 'comprehend'.

### ISSUE THREAD

**Issue by galinagpolyakova** [aws/elastic-load-balancing-tools#30]
>>> print(botocore.__version__)
1.7.48
>>> print(boto3.__version__)
1.4.7

>>> **client = boto3.client('comprehend')**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 66, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 99, in _load_service_model
    api_version=api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/loaders.py", line 378, in load_service_model
    known_service_names=', '.join(sorted(known_services)))
**botocore.exceptions.UnknownServiceError: Unknown service: 'comprehend'.** Valid service names are: acm, apigateway, application-autoscaling, appstream, athena, autoscaling, batch, budgets, ce, clouddirectory, cloudformation, cloudfront, cloudhsm, cloudhsmv2, cloudsearch, cloudsearchdomain, cloudtrail, cloudwatch, codebuild, codecommit, codedeploy, codepipeline, codestar, cognito-identity, cognito-idp, cognito-sync, config, cur, datapipeline, dax, devicefarm, directconnect, discovery, dms, ds, dynamodb, dynamodbstreams, ec2, ecr, ecs, efs, elasticache, elasticbeanstalk, elastictranscoder, elb, elbv2, emr, es, events, firehose, gamelift, glacier, glue, greengrass, health, iam, importexport, inspector, iot, iot-data, kinesis, kinesisanalytics, kms, lambda, lex-models, lex-runtime, lightsail, logs, machinelearning, marketplace-entitlement, marketplacecommerceanalytics, meteringmarketplace, mgh, mobile, mturk, opsworks, opsworkscm, organizations, pinpoint, polly, pricing, rds, redshift, rekognition, resourcegroupstaggingapi, route53, route53domains, s3, sdb, servicecatalog, ses, shield, sms, snowball, sns, sqs, ssm, stepfunctions, storagegateway, sts, support, swf, waf, waf-regional, workdocs, workspaces, xray

**Comment by galinagpolyakova** [comment]
woooohoooo
thank you,  I can't believe that I missed that one, I've tried to upgrade to latest but did not see 1.7.5, super cool, now works.

**Comment by galinagpolyakova** [comment]
oh man, I see what you mean, I raised the bug in ELB tool rather that the main branch. pardon, it was not related to any tools, rather to boto3 itself.

**Comment by renlon** [comment]
glad that it works now. close this issue
