### ISSUE TITLE
Cloud Formation

### ISSUE THREAD

**Issue by vpopiol** [aws/elastic-load-balancing-tools#38]
Is it possible to create the load balancer that forwards to the Lambda with Cloudformation?

Thanks

**Comment by renlon** [comment]
Hi vpopiol, unfortunately, Cloudformation does not support Lambda as target at the moment.  It is on our road map. Before it becomes available, you can either use customer resource or Macro to create a Lambda-target. Thanks for your feedback. 

See more about Custom Resources:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html
See more about Using AWS CloudFormation Macros to Perform Custom Processing on Templates:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-macros.html
