### ISSUE TITLE
how can we use ALB for API level throttling

### ISSUE THREAD

**Issue by vikas-yadav-nice** [aws/elastic-load-balancing-tools#42]
Hi Team ,

I am looking out to implement API level throttling in ALB.
As per documents I couldn't find anything related to API throttling implementation in ALB.

could  you please assist on how to implement API Throttling in ALB.

Thanks,

**Comment by renlon** [comment]
Not sure if git issue is the best platform for this question. 
Could you please open a support case and clarify your question? Assuming you are asking how to handle ELB API throttling?
