### ISSUE TITLE
What is `lambda_error_reason` field as does not exist on the offical ALB access logs schema

### ISSUE THREAD

**Issue by pio2pio** [aws/elastic-load-balancing-tools#44]
I have been investigating recently WAF/ALB logs and according to [this official doc] (https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html) the `lambda_error_reason` field does not exist. But instead `error_reason` it does? 

Then all the Athena tables setup and sql queries relay on `lambda_error_reason` but when chatting with AWS Support they asked me to verify `error_reason` field? Is this the same field or am I missing here something?

**Comment by renlon** [comment]
As you noted from the [public document](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html) that the `lambda_error_reason` field name is supposed to be `error_reason`. 
Will send out a pull request to fix that. Thanks for opening the issue.

**Comment by renlon** [comment]
Fix CR has been merged
