### ISSUE TITLE
TypeError when running the script

### ISSUE THREAD

**Issue by harin-cp** [aws/elastic-load-balancing-tools#45]
I am getting an error "TypeError: a bytes-like object is required, not 'str'" when running this script from cloudshell in AWS. Should I have to modify something? 

---- 
[cloudshell-user@ip-10-0-110-49 classic-load-balancer-consolelink-utility]$ python3 consolelink_classic_load_balancer.py --region us-west-2 --format html
Traceback (most recent call last):
  File "consolelink_classic_load_balancer.py", line 202, in <module>
    main()
  File "consolelink_classic_load_balancer.py", line 200, in main
    get_html(elb_data)
  File "consolelink_classic_load_balancer.py", line 161, in get_html
    html_file.write(html)
TypeError: a bytes-like object is required, not 'str'
[cloudshell-user@ip-10-0-110-49 classic-load-balancer-consolelink-utility]$
------

**Comment by renlon** [comment]
The issue has been resolved by https://github.com/aws/elastic-load-balancing-tools/commit/04d06fdcbe7e3516e21a681292db3cc0975d78a3
