### ISSUE TITLE
Get a "Tag Key cannot start with 'aws:' error

### ISSUE THREAD

**Issue by BlakeWard** [aws/elastic-load-balancing-tools#6]
When I try to use the script to copy my ELB (which was created by ElasticBeanstalk), I get the following exception:

`Traceback (most recent call last):
  File "./copy_classic_load_balancer.py", line 466, in <module>
    main()
  File "./copy_classic_load_balancer.py", line 443, in main
    alb_arn = create_alb(alb_data)
  File "./copy_classic_load_balancer.py", line 291, in create_alb
    response = client.create_load_balancer(**request)
  File "/Users/bward/.local/lib/aws/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/bward/.local/lib/aws/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateLoadBalancer operation: Tag key 'aws:cloudformation:stack-name' cannot start with 'aws:'`

My classic load balancer does have several keys that begin with aws:, but they were all created by ElasticBeanstalk and I don't seem to be able to edit them.

What should I do differently to get the copy script to work?

**Comment by danlindow** [comment]
I can replicate this when trying to add a tag to the Application Load Balancer where the key is prefixed with "aws:". This namespace is reserved for AWS use.  There will need to be further logic in the script to exclude these tags from being passed to the create call.

**Comment by steptan** [comment]
I am having the same issue with CloudFormation-created LBs. CloudFormation creates its own tags that start with AWS:
aws:cloudformation:stack-name
aws:cloudformation:stack-id
aws:cloudformation:logical-id

**Comment by danlindow** [comment]
While this utility can migrate a Classic ELB resource to an Application Load balancer, it does not update update CloudFormation stacks/templates or Elastic Beanstalk environments as part of the migration process.  As such Beanstalk and CloudFormation stacks will need to be updated seperately to utilize Application Load Balancer.   

We are working on an update to the utility to check for both of these conditions(Beanstalk and CloudFormation) and notify users when these conditions occur.

**Comment by coltoncat** [comment]
Our latest update identifies the presence of tags that start with the `aws:` prefix, and prompts to continue without creating them. Currently the only way to migrate an AWS Elastic Beanstalk environment to use ALB is to re-create the environment using ALB, as you can only specify the load-balancer type during environment creation. For more information - refer to: [Configuring an Application Load Balancer](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-applicationloadbalancer.html)

**Comment by duckworth** [comment]
I am getting prompted "Do you want to proceed without AWS reserved tag?", and I am choosing 'y' but I am still getting an error:

`botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateLoadBalancer operation: Tag key 'aws:cloudformation:stack-id' cannot start with 'aws:'`

**Comment by danlindow** [comment]
@duckworth we just pushed a new version up that should fix that issue.  Can you pull down the newest version and run this again?

Thanks!
