### ISSUE TITLE
Assigning elastic IP for loadBalacer kubernetes services

### ISSUE THREAD

**Issue by nurhun** [aws/elastic-load-balancing-tools#60]
I need to deploy ingress-nginx with static IP, as per their doc, 

> Optionally you can set controller.service.loadBalancerIP if you need a static IP for the resulting LoadBalancer.

I've tried it but it doesn't work.

**Comment by lucaspellucci** [comment]
Thanks for you message. I suggest you open an AWS Support case for your query.
