### ISSUE TITLE
Year range is currently 2017 to 2022

### ISSUE THREAD

**Issue by tkrajca** [aws/elastic-load-balancing-tools#65]
Hi,
I believe the cdk template currently generate AWS Glue table with date range 2017-2022 so no s3 data is indexed (unless you store for 2+ years).

https://github.com/aws/elastic-load-balancing-tools/blob/master/log-analysis-elb-cdk-cf-template/stacks/athena_stack.py#L246

**Comment by lucaspellucci** [comment]
Thanks for bringing this up, it has been fixed.
