### ISSUE TITLE
boto3 import error

### ISSUE THREAD

**Issue by steptan** [aws/elastic-load-balancing-tools#8]
Traceback (most recent call last):
  File "./copy_classic_load_balancer.py", line 17, in <module>
    import boto3
ImportError: No module named boto3

To fix, I simply did
pip install boto3

But those less familiar with python might not know to take that step.

**Comment by coltoncat** [comment]
Thanks for calling this out - we will add a message to fail gracefully when the dependency is not present (and also when the requisite version is not present).

**Comment by renlon** [comment]
Thanks for the feedback. We will add prerequisite section in the README and call out boto3 is required by this tool.  Closing this Issue.
